# User.delete_all
Product.delete_all
Cart.delete_all

# travis = User.create(username: "travisprol0", bio: "this is my bio", avatar: "https://www.pinclipart.com/picdir/middle/220-2206914_clip-art-funny-avartars-funny-user-avatar-png.png")
# christiana = User.create(username: "christianamarie", bio: "this is her bio", avatar: "https://avatarfiles.alphacoders.com/547/54795.jpg")

Product.create(user_id: 2, title: "ETC Source Four 10 Degree", brand: "ETC", model: "Source Four 10 Degree",  description: "The ETC Source Four (Source 4) 10 Degree features a standard Source Four ellipsoidal head and a 10 degree lens tube. Source Four's revolutionary technology gives you a clean white beam for unequaled imaging, crisp pattern projection, and a bright, even field.  These features combine to make the coolest beam available in an ellipsoidal- meaning gels, patterns, and shutters last longer and your performance space stays cooler.", price: 350.00, quantity: 7, category: "lighting", image: "https://www.stagelightingstore.com/10278-large_default/etc-source-four-ellipsoidal-26-degree-black-7060a1008.jpg")
Product.create(user_id: 2, title: "ETC Source Four LED Lustr 2", brand: "ETC", model: "7461A1051", description: "If you're looking to upgrade your tungsten lighting spotlights to LED, the ETC Source Four LED Lustr 2 is a great option.The Lustr 2 uses the same shutter blade, lens barrel and optics as a traditional Source Four, making the transition from tungsten to LED easier. There's no need to throw out or sell off your current lens tubes, as they will work seamlessly with the Lustr 2. If you're worried about matching the light of an HPL lamp, this fixture has you covered. ETC added lime green LEDs to the mix, which improves the overall lumen output in open white and lighter tints, allowing you to match the color of a conventional Source Four. The Lustr 2 also utilizes extra red to produce ambers, straws & pinks that allow for great sunsets, moonlight and dramatic scenes.", price: 1895.00,  quantity: 4, category: "lighting", image: "https://cdn01.usedlighting.com/products/images/thumbs/ncm_f5cb4b349306c6.jpg")
Product.create(user_id: 2, title: "JBL EON15 G2 Bi-Amped Speaker 400W", brand: "JBL", model: "EON15 G2",  description: 'The JBL EON15 G2, delivers 300 watts of power to a 15" neodymium Differential Drive LF driver. The driver boasts a dual neodymium magnet and dual voice coil motor that efficiently delivers high output from a lightweight woofer. Meanwhile, the HF amplifier delivers 100 watts of power to a 1.75" titanium diaphragm compressiondriver with Ferro-fluid cooling.', price: 295.00,  quantity: 2, category: "sound", image: "https://cdn01.usedlighting.com/products/images/thumbs/ncm_f57f73ce160ece.jpg")
Product.create(user_id: 2, title: "Yamaha PM5D-RH Digital Mixing Console #1", brand: "Yamaha", model: "PM5D-RH",  description: 'The PM5D-RH is a full-digital SR mixing console that takes advantage of cutting-edge digital audio processing technology. 24-bit linear AD/DA converters are used to deliver up to 110 dB of dynamic range and amazing sound quality. As input channels, it provides 48 monaural channels, four stereo channels, and four stereo channels for effect return. As output channels, it provides 24 MIX channels, eight MATRIX channels, and two STEREO channels. The PM5D can be used in a wide range of applications. You can assign desired channels to be controlled by the eight DCA faders on the panel, and use them as group faders.', price: 9550.00,  quantity: 1, category: "sound", image: "https://cdn01.usedlighting.com/products/images/thumbs/ncm_f5d928aaf11c15.jpg")
Product.create(user_id: 2, title: "QSC GX5 Power Amplifier", brand: "QSC", model: "GX5",  description: 'GX Series amplifiers are ideal for professional entertainers who require maximum performance and portability on a limited budget. The hallmarks of the QSC brand – professional audio quality, meticulous engineering, precision manufacturing and long-term reliability - are all intrinsic to GX. Add contemporary styling, multiple input/output options, light weight, and advanced protection circuitry, and the GX Series clearly represents real value – something everyone can use.', price: 350.00,  quantity: 1, category: "sound", image: "https://cdn01.usedlighting.com/products/images/thumbs/ncm_f5ddba6b960dc3.jpg")
Product.create(user_id: 2, title: 'ETC Source Four Top Hat 14"', brand: "City Theatrical", model: "2451", description: 'Top Hats serve two functions in entertainment lighting:  To control light spill or to reduce the viewing angle to the lens.  Sometimes poor fixture optics or poorly maintained lenses can cause light to be directed into the audience or onto scenery, and top hats can help control that.  It is also often objectionable to the audience or camera to see the bright source of the light and top hats can shield the bright source from view.  Top hats and half top hats are flocked on the interior to reduce light reflection. ', price: 30.00,  quantity: 24, category: "lighting", image: "https://cdn01.usedlighting.com/products/images/thumbs/ncm_f57f72f55e3b98.jpg")

